version: '3.7'
services:
  accountant_db:
    container_name: recommendation_db
    image: mysql:8.0
    environment:
       MYSQL_USER: "${MYSQL_USERNAME}"
       MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
       MYSQL_DATABASE: "${MYSQL_DATABASE}"
    env_file:
      - .env
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "${API_LOCAL_PORT}:${API_LOCAL_PORT}"
    restart: always
  app:
    build:
      context: .
    container_name: recommendation_service_app
    image: recommendation-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - recommendation_db
    environment:
       MYSQL_USER: "${MYSQL_USERNAME}"
       MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
       MYSQL_DATABASE: "${MYSQL_DATABASE}"
       MYSQL_PORT: "${MYSQL_PORT}"
volumes:
  dbvol: